//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchCheck
    {
        public int Id { get; set; }
        public int RecordID { get; set; }
        public int InterviewRecordID { get; set; }
        public string Name { get; set; }
        public int Num { get; set; }
        public System.DateTime Date { get; set; }
        public string Service { get; set; }
        public bool Matched { get; set; }
    }
}
